[package]
name = "busy_beaver"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "1.0.0", default-features = false, features = [
    "debug",
    "display",
    "error",
    "from",
] }

thousands = "0.2.0"
