[package]
name = "busy_beaver"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = { version = "1.0.0", default-features = false, features = [
    "debug",
    "display",
    "error",
    "from",
] }
png = "0.17.16"

thousands = "0.2.0"
wasm-bindgen = "0.2.100"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
